import { D1CreateEndpoint } from "chanfana";
import { createPrismaClient, type PrismaClient } from "../../lib/prisma";
import { HandleArgs } from "../../types";
import { TaskModel, serializeTask, type TaskApiShape } from "./base";
import { invalidateTasksCacheAfterWrite } from "./invalidation";

export class TaskCreate extends D1CreateEndpoint<HandleArgs> {
	_meta = {
		model: TaskModel,
		fields: TaskModel.schema.pick({
			// id is intentionally excluded — auto-generated by the database
			name: true,
			slug: true,
			description: true,
			completed: true,
			due_date: true,
		}),
	};

	private prisma?: PrismaClient;

	public override async handle(...args: HandleArgs) {
		const [c] = args;
		this.prisma = createPrismaClient(c.env.DB);
		const res = await super.handle(...args);
		await invalidateTasksCacheAfterWrite(c, "tasks.create");
		return res;
	}

	public override async create(data: TaskApiShape): Promise<TaskApiShape> {
		const row = await this.prisma!.task.create({
			data: {
				name: data.name,
				slug: data.slug,
				description: data.description,
				completed: data.completed,
				dueDate: new Date(data.due_date),
			},
		});
		return serializeTask(row);
	}
}
